/**
 * Invoice Routes — CRUD, stats, duplicate, and print-based PDF generation
 * PDF is generated by the browser's built-in Print-to-PDF (no Puppeteer needed)
 */

const express = require('express');
const { db }  = require('../database/db');
const { authenticateToken } = require('./auth');

const router = express.Router();

// ── Auto-generate next invoice number ─────────────────────────────────────────
function nextInvoiceNumber() {
  const s      = db.getAllSettings();
  const prefix = s.invoice_prefix || 'INV';
  const start  = parseInt(s.invoice_start) || 1001;
  const all    = db.all('invoices').filter(i => i.invoice_number?.startsWith(prefix + '-'));
  if (!all.length) return `${prefix}-${start}`;
  const nums   = all.map(i => parseInt(i.invoice_number.split('-').pop()) || 0);
  return `${prefix}-${Math.max(...nums) + 1}`;
}

// ── Calculate totals from items ───────────────────────────────────────────────
function calcTotals(items, discountType, discountValue) {
  let subtotal = 0, taxTotal = 0;
  const out = (items || []).map((item, idx) => {
    const qty    = parseFloat(item.quantity)   || 0;
    const price  = parseFloat(item.unit_price) || 0;
    const taxPct = parseFloat(item.tax_pct)    || 0;
    const base   = qty * price;
    const tax    = base * (taxPct / 100);
    subtotal += base;
    taxTotal += tax;
    return { ...item, quantity: qty, unit_price: price, tax_pct: taxPct, tax_amount: tax, total: base + tax, sort_order: idx };
  });
  const discAmt = discountType === 'percentage'
    ? subtotal * ((parseFloat(discountValue) || 0) / 100)
    : (parseFloat(discountValue) || 0);
  return { items: out, subtotal, taxTotal, discountAmount: discAmt, grandTotal: subtotal + taxTotal - discAmt };
}

// ═══════════════════════════════════════════════════════════════════════════════
// PREVIEW — No auth needed (served in iframe from the same origin)
// ═══════════════════════════════════════════════════════════════════════════════
router.get('/:id/preview', (req, res) => {
  const invoice = db.find('invoices', req.params.id);
  if (!invoice) return res.status(404).send('<h2 style="font-family:sans-serif;padding:40px">Invoice not found</h2>');
  const items   = db.filter('invoice_items', i => String(i.invoice_id) === String(req.params.id))
                    .sort((a, b) => a.sort_order - b.sort_order);
  const client  = invoice.client_id ? db.find('clients', invoice.client_id) : null;
  const merged  = { ...invoice, client_gstin: client?.gstin || '', client_phone: client?.phone || '', client_email: client?.email || '' };
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.send(buildInvoiceHTML(merged, items, db.getAllSettings(), false));
});

// PRINT VIEW — Auto-triggers browser print dialog (for PDF download)
router.get('/:id/print', (req, res) => {
  const invoice = db.find('invoices', req.params.id);
  if (!invoice) return res.status(404).send('<h2>Invoice not found</h2>');
  const items   = db.filter('invoice_items', i => String(i.invoice_id) === String(req.params.id))
                    .sort((a, b) => a.sort_order - b.sort_order);
  const client  = invoice.client_id ? db.find('clients', invoice.client_id) : null;
  const merged  = { ...invoice, client_gstin: client?.gstin || '', client_phone: client?.phone || '', client_email: client?.email || '' };
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.send(buildInvoiceHTML(merged, items, db.getAllSettings(), true)); // true = auto-print
});

// PDF DOWNLOAD — Opens print view (works on all devices including mobile)
router.get('/:id/pdf', async (req, res) => {
  // Redirect to print view which auto-triggers browser print dialog
  // This is mobile-safe and works without Puppeteer/headless browser
  res.redirect(`/api/invoices/${req.params.id}/print`);
});

// All routes below require auth
router.use(authenticateToken);

// ── GET /api/invoices/stats ────────────────────────────────────────────────────
router.get('/stats', (req, res) => {
  const all    = db.all('invoices');
  const paid   = all.filter(i => i.status === 'paid');
  const unpaid = all.filter(i => i.status === 'unpaid');
  const draft  = all.filter(i => i.status === 'draft');
  const sum    = arr => arr.reduce((s, i) => s + (parseFloat(i.grand_total) || 0), 0);

  const recent = all.slice().sort((a, b) => new Date(b.created_at) - new Date(a.created_at)).slice(0, 5).map(inv => {
    const c = inv.client_id ? db.find('clients', inv.client_id) : null;
    return { ...inv, client_email: c?.email || '' };
  });

  res.json({
    total:  all.length,
    paid:   { count: paid.length,   amount: sum(paid) },
    unpaid: { count: unpaid.length, amount: sum(unpaid) },
    draft:  draft.length,
    recent
  });
});

// ── GET /api/invoices/next-number ─────────────────────────────────────────────
router.get('/next-number', (req, res) => {
  res.json({ invoice_number: nextInvoiceNumber() });
});

// ── GET /api/invoices ─────────────────────────────────────────────────────────
router.get('/', (req, res) => {
  const { search, status, from_date, to_date, page = 1, limit = 15 } = req.query;
  let invoices = db.all('invoices');

  if (search) {
    const s = search.toLowerCase();
    invoices = invoices.filter(i => i.invoice_number?.toLowerCase().includes(s) || i.client_name?.toLowerCase().includes(s));
  }
  if (status && status !== 'all') invoices = invoices.filter(i => i.status === status);
  if (from_date) invoices = invoices.filter(i => i.date >= from_date);
  if (to_date)   invoices = invoices.filter(i => i.date <= to_date);

  // Sort newest first
  invoices.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

  const total  = invoices.length;
  const pg     = parseInt(page);
  const lim    = parseInt(limit);
  const paged  = invoices.slice((pg - 1) * lim, pg * lim).map(inv => {
    const c = inv.client_id ? db.find('clients', inv.client_id) : null;
    return { ...inv, client_email: c?.email || '', client_phone: c?.phone || '' };
  });

  res.json({ invoices: paged, total, page: pg, pages: Math.ceil(total / lim) });
});

// ── GET /api/invoices/:id ─────────────────────────────────────────────────────
router.get('/:id', (req, res) => {
  const inv = db.find('invoices', req.params.id);
  if (!inv) return res.status(404).json({ error: 'Invoice not found' });
  const items = db.filter('invoice_items', i => String(i.invoice_id) === String(req.params.id))
                  .sort((a, b) => a.sort_order - b.sort_order);
  const c = inv.client_id ? db.find('clients', inv.client_id) : null;
  res.json({ ...inv, items, client_gstin: c?.gstin || '', client_email: c?.email || '', client_phone: c?.phone || '' });
});

// ── POST /api/invoices ────────────────────────────────────────────────────────
router.post('/', (req, res) => {
  const { invoice_number, date, due_date, client_id, client_name, client_address,
    status = 'unpaid', discount_type = 'percentage', discount_value = 0, notes = '', items = [] } = req.body;

  if (!client_name?.trim()) return res.status(400).json({ error: 'Client name is required' });
  if (!date)                return res.status(400).json({ error: 'Invoice date is required' });
  if (!due_date)            return res.status(400).json({ error: 'Due date is required' });

  const invNum = (invoice_number || '').trim() || nextInvoiceNumber();

  // Check duplicate number
  if (db.all('invoices').some(i => i.invoice_number === invNum)) {
    return res.status(409).json({ error: `Invoice number "${invNum}" already exists` });
  }

  const { items: pi, subtotal, taxTotal, discountAmount, grandTotal } = calcTotals(items, discount_type, discount_value);

  const inv = db.insert('invoices', {
    invoice_number: invNum, date, due_date,
    client_id: client_id || null, client_name: client_name.trim(), client_address: client_address || '',
    status, subtotal, discount_type, discount_value: parseFloat(discount_value) || 0,
    discount_amount: discountAmount, tax_total: taxTotal, grand_total: grandTotal, notes: notes || ''
  });

  const savedItems = pi.map(item => db.insert('invoice_items', { invoice_id: inv.id, ...item }));
  res.status(201).json({ ...inv, items: savedItems });
});

// ── PUT /api/invoices/:id ─────────────────────────────────────────────────────
router.put('/:id', (req, res) => {
  if (!db.find('invoices', req.params.id)) return res.status(404).json({ error: 'Invoice not found' });

  const { invoice_number, date, due_date, client_id, client_name, client_address,
    status, discount_type, discount_value, notes, items = [] } = req.body;
  const { items: pi, subtotal, taxTotal, discountAmount, grandTotal } = calcTotals(items, discount_type, discount_value);

  const inv = db.update('invoices', req.params.id, {
    invoice_number, date, due_date, client_id: client_id || null,
    client_name, client_address: client_address || '', status,
    subtotal, discount_type, discount_value: parseFloat(discount_value) || 0,
    discount_amount: discountAmount, tax_total: taxTotal, grand_total: grandTotal, notes: notes || ''
  });

  // Replace items
  db.deleteWhere('invoice_items', i => String(i.invoice_id) === String(req.params.id));
  const savedItems = pi.map(item => db.insert('invoice_items', { invoice_id: parseInt(req.params.id), ...item }));

  res.json({ ...inv, items: savedItems });
});

// ── DELETE /api/invoices/:id ──────────────────────────────────────────────────
router.delete('/:id', (req, res) => {
  if (!db.find('invoices', req.params.id)) return res.status(404).json({ error: 'Invoice not found' });
  db.delete('invoices', req.params.id);
  db.deleteWhere('invoice_items', i => String(i.invoice_id) === String(req.params.id));
  res.json({ message: 'Invoice deleted' });
});

// ── POST /api/invoices/:id/duplicate ─────────────────────────────────────────
router.post('/:id/duplicate', (req, res) => {
  const orig = db.find('invoices', req.params.id);
  if (!orig) return res.status(404).json({ error: 'Invoice not found' });
  const origItems = db.filter('invoice_items', i => String(i.invoice_id) === String(req.params.id));

  const inv = db.insert('invoices', {
    ...orig, id: undefined, created_at: undefined, updated_at: undefined,
    invoice_number: nextInvoiceNumber(),
    date:           new Date().toISOString().split('T')[0],
    status:         'draft'
  });

  const savedItems = origItems.map(item => db.insert('invoice_items', {
    ...item, id: undefined, created_at: undefined, updated_at: undefined,
    invoice_id: inv.id
  }));

  res.status(201).json({ ...inv, items: savedItems });
});

// ── PATCH /api/invoices/:id/status ────────────────────────────────────────────
router.patch('/:id/status', (req, res) => {
  const { status } = req.body;
  if (!['paid','unpaid','draft','cancelled'].includes(status)) return res.status(400).json({ error: 'Invalid status' });
  db.update('invoices', req.params.id, { status });
  res.json({ message: 'Status updated' });
});

// ═══════════════════════════════════════════════════════════════════════════════
// ── Invoice HTML Builder ──────────────────────────────────────────────────────
// Generates a standalone, self-contained HTML invoice that exactly matches the
// provided design. When autoPrint=true the page auto-triggers the print dialog.
// ═══════════════════════════════════════════════════════════════════════════════
function buildInvoiceHTML(invoice, items, settings, autoPrint = false) {
  const cur = settings.currency || '₹';
  const esc = s => String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const fmt = n  => `${cur}${parseFloat(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const fmtDate = d => { try { return new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}); } catch { return d||''; }};

  const logoSrc = settings.logo_data?.startsWith('data:')
    ? settings.logo_data
    : `data:image/svg+xml;base64,${Buffer.from(DEFAULT_SVG_LOGO).toString('base64')}`;

  const taxLabel = esc(settings.tax_label || 'GST');

  // Check if any item has GST
  const hasGST = items.some(item => parseFloat(item.tax_pct) > 0);

  const rows = items.map((item, i) => {
    const showTaxCell = parseFloat(item.tax_pct) > 0;
    return `
    <tr class="${i%2===0?'row-even':'row-odd'}">
      <td class="tc num-col">${i+1}</td>
      <td class="name-col">${esc(item.name)}</td>
      <td class="tc">${item.quantity}</td>
      <td class="tr">${fmt(item.unit_price)}</td>
      ${hasGST ? `<td class="tc">${showTaxCell ? item.tax_pct+'%' : '—'}</td>` : ''}
      <td class="tr total-col">${fmt(item.total)}</td>
    </tr>`;
  }).join('');

  const bankRows = [
    ['Bank Name', settings.bank_name],
    ['Account No.', settings.bank_account],
    ['IFSC Code', settings.bank_ifsc],
    ['Branch', settings.bank_branch],
    ...(settings.bank_upi ? [['UPI ID', settings.bank_upi]] : [])
  ].filter(([,v]) => v).map(([l,v]) => `
    <div class="bank-row">
      <span class="bank-label">${esc(l)}</span>
      <span class="bank-value">${esc(String(v))}</span>
    </div>`).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Invoice ${esc(invoice.invoice_number)}</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"/>
<style>
  *{margin:0;padding:0;box-sizing:border-box;}
  body{font-family:'Inter',Arial,sans-serif;background:#F4F4F4;min-height:100vh;display:flex;flex-direction:column;align-items:center;padding:24px 16px;}

  /* ── Shell ── */
  .invoice-shell{width:100%;max-width:820px;background:#fff;box-shadow:0 8px 40px rgba(43,129,197,0.15);border-radius:6px;overflow:hidden;display:flex;flex-direction:column;min-height:calc(100vh - 48px);}

  /* ── Toolbar ── */
  .toolbar{width:100%;max-width:820px;display:flex;gap:10px;margin-bottom:14px;justify-content:flex-end;flex-wrap:wrap;}
  .toolbar button{padding:10px 20px;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;font-family:inherit;transition:all 0.2s;display:flex;align-items:center;gap:6px;}
  .btn-print{background:linear-gradient(135deg,#1F5F99,#2B81C5);color:white;}
  .btn-print:hover{transform:translateY(-1px);box-shadow:0 6px 20px rgba(43,129,197,0.4);}
  .btn-close{background:#f3f4f6;color:#374151;border:1.5px solid #e5e7eb;}
  .btn-close:hover{background:#e5e7eb;}

  /* ── Header ── */
  .inv-header{background:linear-gradient(135deg,#1F5F99 0%,#2B81C5 100%);padding:32px 40px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:16px;}
  .inv-header-left{display:flex;align-items:center;gap:14px;}
  .inv-logo-box{width:56px;height:56px;background:rgba(255,255,255,0.15);border-radius:12px;border:2px solid rgba(255,255,255,0.25);overflow:hidden;padding:4px;display:flex;align-items:center;justify-content:center;flex-shrink:0;}
  .inv-logo-box img{width:100%;height:100%;object-fit:contain;}
  .inv-company-name{font-size:18px;font-weight:800;color:white;letter-spacing:0.5px;}
  .inv-company-tag{font-size:10px;color:rgba(255,255,255,0.6);letter-spacing:2px;text-transform:uppercase;margin-top:2px;}
  .inv-header-right{text-align:right;}
  .inv-title{font-size:40px;font-weight:900;letter-spacing:4px;color:white;line-height:1;}
  .inv-number{font-size:12px;color:rgba(255,255,255,0.7);margin-top:4px;letter-spacing:1px;}

  /* ── Info Band ── */
  .inv-info-band{background:#eef4fa;border-bottom:3px solid #2B81C5;padding:24px 40px;display:flex;justify-content:space-between;align-items:flex-start;gap:24px;flex-wrap:wrap;}
  .inv-billed{flex:1;min-width:160px;}
  .inv-details{min-width:200px;flex-shrink:0;}
  .band-label{font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#1F5F99;border-left:3px solid #2B81C5;padding-left:8px;margin-bottom:10px;}
  .client-name{font-size:17px;font-weight:700;color:#333;margin-bottom:4px;}
  .client-addr{font-size:13px;color:#555;line-height:1.7;white-space:pre-line;}
  .client-gstin{margin-top:5px;font-size:12px;color:#555;}
  .detail-table{width:100%;border-collapse:collapse;}
  .detail-table td{font-size:13px;padding:4px 0;}
  .detail-label{font-weight:600;color:#555;width:100px;}
  .detail-value{font-weight:700;color:#1F5F99;text-align:right;}

  /* ── Items ── */
  .items-section{padding:24px 40px 0;}
  .items-scroll{overflow-x:auto;-webkit-overflow-scrolling:touch;}
  .items-table{width:100%;border-collapse:collapse;min-width:400px;}
  .items-table thead tr{background:linear-gradient(135deg,#1F5F99 0%,#2B81C5 100%);}
  .items-table th{padding:12px 16px;font-size:11px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:rgba(255,255,255,0.9);text-align:left;}
  .items-table td{padding:14px 16px;font-size:13px;color:#333;}
  .row-even{background:#fff;}
  .row-odd{background:#f4f8fc;}
  .items-table tr{border-bottom:1px solid #e2eaf2;}
  .num-col{width:64px;text-align:center;color:#888;font-weight:600;}
  .name-col{font-weight:600;}
  .total-col{font-weight:700;color:#1F5F99;}
  .tc{text-align:center;}
  .tr{text-align:right;}

  /* ── Items table header rendering (with conditional GST col) ── */

  .bottom-section{padding:24px 40px;display:flex;justify-content:space-between;align-items:flex-start;gap:32px;flex-wrap:wrap;margin-top:6px;}
  .bank-panel{flex:1;min-width:200px;}
  .totals-panel{min-width:260px;flex-shrink:0;}
  .section-label{font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#1F5F99;border-left:3px solid #2B81C5;padding-left:8px;margin-bottom:12px;}
  .bank-box{background:#eef4fa;border:1px solid #9CBFDE;border-radius:8px;padding:16px 18px;}
  .bank-row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #d0e4f0;font-size:13px;}
  .bank-row:last-child{border-bottom:none;}
  .bank-label{font-weight:600;color:#555;}
  .bank-value{color:#1F5F99;font-weight:600;text-align:right;margin-left:12px;}
  .totals-box{background:#eef4fa;border:1px solid #9CBFDE;border-radius:8px;overflow:hidden;}
  .totals-row{display:flex;justify-content:space-between;padding:12px 16px;border-bottom:1px solid #d0e4f0;font-size:14px;}
  .totals-label{color:#555;font-weight:500;}
  .totals-value{font-weight:600;color:#1F5F99;}
  .discount-value{font-weight:600;color:#ef4444;}
  .grand-row{background:linear-gradient(135deg,#1F5F99 0%,#2B81C5 100%);padding:16px 18px;display:flex;justify-content:space-between;align-items:center;}
  .grand-label{color:rgba(255,255,255,0.9);font-weight:700;font-size:15px;}
  .grand-value{color:white;font-weight:800;font-size:22px;}



  /* ── Footer ── */
  .inv-footer{background:linear-gradient(135deg,#1F5F99 0%,#2B81C5 100%);padding:24px 40px;display:flex;justify-content:space-between;align-items:center;margin-top:auto;flex-wrap:wrap;gap:16px;}
  .footer-thanks{color:rgba(255,255,255,0.9);font-size:14px;font-style:italic;line-height:1.6;}
  .footer-contact{font-size:12px;opacity:0.75;margin-top:4px;}
  .footer-brand{text-align:right;}
  .footer-name{font-size:17px;font-weight:800;color:white;letter-spacing:1.5px;}
  .footer-tag{font-size:10px;color:rgba(255,255,255,0.6);letter-spacing:2.5px;text-transform:uppercase;margin-top:4px;}

  /* ── Print ── */
  @media print {
    body{background:white;padding:0;margin:0;}
    .invoice-shell{box-shadow:none;width:100%;max-width:100%;border-radius:0;min-height:100vh;}
    .no-print{display:none!important;}
    .items-scroll{overflow:visible;}
    .items-table{min-width:0;}
  }

  /* ── Mobile (≤ 600px) ── */
  @media (max-width:600px){
    body{padding:0;background:#fff;}
    .invoice-shell{border-radius:0;box-shadow:none;}
    .toolbar{padding:10px 12px;background:#F4F4F4;justify-content:stretch;margin-bottom:0;}
    .toolbar button{flex:1;justify-content:center;font-size:12px;padding:10px 12px;}
  }
</style>
</head>
<body>

<!-- Toolbar -->
<div class="toolbar no-print">
  <button class="btn-print" onclick="window.print()">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg>
    Print / Save as PDF
  </button>
  <button class="btn-close" onclick="window.close()">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
    Close
  </button>
</div>

<div class="invoice-shell">

  <!-- HEADER -->
  <div class="inv-header">
    <div class="inv-header-left">
      <div class="inv-logo-box"><img src="${logoSrc}" alt="Logo"/></div>
      <div>
        <div class="inv-company-name">${esc(settings.company_name||'YOUR COMPANY')}</div>
        <div class="inv-company-tag">${esc(settings.company_tagline||'')}</div>
      </div>
    </div>
    <div class="inv-header-right">
      <div class="inv-title">INVOICE</div>
      <div class="inv-number"># ${esc(invoice.invoice_number)}</div>
    </div>
  </div>

  <!-- INFO BAND -->
  <div class="inv-info-band">
    <div class="inv-billed">
      <div class="band-label">Billed To</div>
      <div class="client-name">${esc(invoice.client_name)}</div>
      <div class="client-addr">${esc(invoice.client_address||'')}</div>
      ${invoice.client_gstin ? `<div class="client-gstin"><strong>GSTIN:</strong> ${esc(invoice.client_gstin)}</div>` : ''}
    </div>
    <div class="inv-details">
      <div class="band-label">Invoice Details</div>
      <table class="detail-table">
        ${[
          ['Invoice No.', esc(invoice.invoice_number)],
          ['Invoice Date', fmtDate(invoice.date)],
          ['Due Date', fmtDate(invoice.due_date)]
        ].map(([l,v]) => `<tr><td class="detail-label">${l}</td><td class="detail-value">${v}</td></tr>`).join('')}
      </table>
    </div>
  </div>

  <!-- ITEMS TABLE -->
  <div class="items-section">
    <div class="items-scroll">
      <table class="items-table">
        <thead>
          <tr>
            ${['Sr. No.','Service / Product','Qty','Unit Price',...(hasGST?[taxLabel+'%']:[]),'Total'].map((h,i) => {
              const isNum = i===0;
              const isRight = i>=3&&!isNum;
              const cls = isNum?'tc':(i===2?'tc':(i===3?'tr':(i===4&&hasGST?'tc':'tr')));
              return `<th class="${cls}">${h}</th>`;
            }).join('')}
          </tr>
        </thead>
        <tbody>
          ${rows || `<tr><td colspan="${hasGST?6:5}" style="padding:20px;text-align:center;color:#888;font-size:12px;">No items added</td></tr>`}
        </tbody>
      </table>
    </div>
  </div>

  <!-- BANK + TOTALS -->
  <div class="bottom-section">
    <div class="bank-panel">
      <div class="section-label">Payment Details</div>
      <div class="bank-box">${bankRows || '<div class="bank-row"><span class="bank-label" style="color:#888;">No bank details configured</span></div>'}</div>
    </div>
    <div class="totals-panel">
      <div class="totals-box">
        <div class="totals-row">
          <span class="totals-label">Subtotal</span>
          <span class="totals-value">${fmt(invoice.subtotal)}</span>
        </div>
        ${parseFloat(invoice.tax_total) > 0 ? `
        <div class="totals-row">
          <span class="totals-label">${taxLabel} Total</span>
          <span class="totals-value">${fmt(invoice.tax_total)}</span>
        </div>` : ''}
        ${parseFloat(invoice.discount_amount) > 0 ? `
        <div class="totals-row">
          <span class="totals-label">Discount${invoice.discount_type==='percentage'?` (${invoice.discount_value}%)`:'(Fixed)'}</span>
          <span class="discount-value">- ${fmt(invoice.discount_amount)}</span>
        </div>` : ''}
        <div class="grand-row">
          <span class="grand-label">Grand Total</span>
          <span class="grand-value">${fmt(invoice.grand_total)}</span>
        </div>
      </div>
    </div>
  </div>

  <!-- FOOTER -->
  <div class="inv-footer">
    <div class="footer-thanks">
      ✨ Thank you for choosing us!
      <div class="footer-contact">${esc(settings.company_email||'')}${settings.company_phone ? ' &nbsp;|&nbsp; ' + esc(settings.company_phone) : ''}</div>
    </div>
    <div class="footer-brand">
      <div class="footer-name">${esc(settings.company_name||'')}</div>
      <div class="footer-tag">${esc(settings.company_tagline||'')}</div>
    </div>
  </div>

</div><!-- end invoice-shell -->

${autoPrint ? `
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<script>
window.addEventListener("load", () => {
  const toolbar = document.querySelector('.toolbar');
  if (toolbar) toolbar.style.display = 'none';

  setTimeout(() => {
    const element = document.querySelector('.invoice-shell');
    
    // Force body to desktop width to ensure perfect rendering without absolute positioning bugs
    const origBodyWidth = document.body.style.width;
    const origBodyPadding = document.body.style.padding;
    const origMargin = element.style.margin;
    
    document.body.style.width = '800px';
    document.body.style.padding = '0';
    element.style.margin = '0';

    const opt = {
      margin:       0,
      filename:     'Invoice-${esc(invoice.invoice_number)}.pdf',
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true, scrollX: 0, scrollY: 0, windowWidth: 800 },
      jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    };
    
    html2pdf().set(opt).from(element).save().then(() => {
      // Restore styles
      document.body.style.width = origBodyWidth;
      document.body.style.padding = origBodyPadding;
      element.style.margin = origMargin;
      
      if (toolbar) toolbar.style.display = 'flex';
      setTimeout(() => window.close(), 1000); // Close the auto-print tab automatically
    });
  }, 800);
});
</script>` : ''}
</body>
</html>`;
}

// Default lightning bolt SVG logo
const DEFAULT_SVG_LOGO = `<svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg">
  <rect width="80" height="80" rx="12" fill="#1F5F99"/>
  <polygon points="46,8 20,44 38,44 28,72 62,34 44,34 56,8" fill="white"/>
</svg>`;

module.exports = router;
